export function juniorPerformance(result) {
  return [
    {
      name: "English Language",
      code: "FJS_001",
      id: "001",
      continuousAssessmentScore: result[1],
      examScore: result[2],
      totalWeightedAverage: result[3],
    },
    {
      name: "Mathematics",
      code: "FJS_002",
      id: "002",
      continuousAssessmentScore: result[4],
      examScore: result[5],
      totalWeightedAverage: result[6],
    },
    {
      name: "Yoruba Language",
      code: "FJS_003",
      id: "003",
      continuousAssessmentScore: result[7],
      examScore: result[8],
      totalWeightedAverage: result[9],
    },
    {
      name: "Basic Science",
      code: "FJS_004",
      id: "004",
      continuousAssessmentScore: result[10],
      examScore: result[11],
      totalWeightedAverage: result[12],
    },
    {
      name: "Basic Tech.",
      code: "FJS_005",
      id: "005",
      continuousAssessmentScore: result[13],
      examScore: result[14],
      totalWeightedAverage: result[15],
    },
    {
      name: "P.H.E",
      code: "FJS_006",
      id: "006",
      continuousAssessmentScore: result[16],
      examScore: result[17],
      totalWeightedAverage: result[18],
    },
    {
      name: "Computer Studies",
      code: "FJS_007",
      id: "007",
      continuousAssessmentScore: result[19],
      examScore: result[20],
      totalWeightedAverage: result[21],
    },
    {
      name: "Home Economics",
      code: "FJS_008",
      id: "008",
      continuousAssessmentScore: result[22],
      examScore: result[23],
      totalWeightedAverage: result[24],
    },
    {
      name: "Agric. Science",
      code: "FJS_009",
      id: "009",
      continuousAssessmentScore: result[25],
      examScore: result[26],
      totalWeightedAverage: result[27],
    },
    {
      name: "I.R.S",
      code: "FJS_010",
      id: "010",
      continuousAssessmentScore: result[28],
      examScore: result[29],
      totalWeightedAverage: result[30],
    },
    {
      name: "Social Studies",
      code: "FJS_011",
      id: "011",
      continuousAssessmentScore: result[31],
      examScore: result[32],
      totalWeightedAverage: result[33],
    },
    {
      name: "Civic Education",
      code: "FJS_012",
      id: "012",
      continuousAssessmentScore: result[34],
      examScore: result[35],
      totalWeightedAverage: result[36],
    },
    {
      name: "Creative and Cultural Arts",
      code: "FJS_013",
      id: "013",
      continuousAssessmentScore: result[37],
      examScore: result[38],
      totalWeightedAverage: result[39],
    },
    {
      name: "Business Studies",
      code: "FJS_014",
      id: "014",
      continuousAssessmentScore: result[40],
      examScore: result[41],
      totalWeightedAverage: result[42],
    },
    {
      name: "French",
      code: "FJS_015",
      id: "015",
      continuousAssessmentScore: result[43],
      examScore: result[44],
      totalWeightedAverage: result[45],
    },
    {
      name: "Arabic",
      code: "FJS_016",
      id: "016",
      continuousAssessmentScore: result[46],
      examScore: result[47],
      totalWeightedAverage: result[48],
    },
    {
      name: "Quran and Hadith",
      code: "FJS_017",
      id: "017",
      continuousAssessmentScore: result[49],
      examScore: result[50],
      totalWeightedAverage: result[51],
    },
    {
      name: "Diction",
      code: "FJS_018",
      id: "018",
      continuousAssessmentScore: result[52],
      examScore: result[53],
      totalWeightedAverage: result[54],
    },
    {
      name: "History",
      code: "FJS_019",
      id: "019",
      continuousAssessmentScore: result[55],
      examScore: result[56],
      totalWeightedAverage: result[57],
    },
  ];
}

export function seniorPerformance(result) {
  return [
    {
      name: "Financial Accounting",
      code: "FSS_018",
      id: "018",
      continuousAssessmentScore: result[1],
      examScore: result[2],
      totalWeightedAverage: result[3],
    },
    {
      name: "Agric. Science",
      code: "FSS_015",
      id: "015",
      continuousAssessmentScore: result[4],
      examScore: result[5],
      totalWeightedAverage: result[6],
    },
    {
      name: "Animal Husbandry",
      code: "FSS_020",
      id: "021",
      continuousAssessmentScore: result[7],
      examScore: result[8],
      totalWeightedAverage: result[9],
    },
    {
      name: "Arabic",
      code: "FSS_012",
      id: "012",
      continuousAssessmentScore: result[10],
      examScore: result[11],
      totalWeightedAverage: result[12],
    },
    {
      name: "Biology",
      code: "FSS_003",
      id: "003",
      continuousAssessmentScore: result[13],
      examScore: result[14],
      totalWeightedAverage: result[15],
    },
    {
      name: "Catering Craft Pra.",
      code: "FSS_003",
      id: "021",
      continuousAssessmentScore: result[16],
      examScore: result[17],
      totalWeightedAverage: result[18],
    },
    {
      name: "Chemistry",
      code: "FSS_005",
      id: "005",
      continuousAssessmentScore: result[19],
      examScore: result[20],
      totalWeightedAverage: result[21],
    },
    {
      name: "Civic Education",
      code: "FSS_008",
      id: "008",
      continuousAssessmentScore: result[22],
      examScore: result[23],
      totalWeightedAverage: result[24],
    },
    {
      name: "Commerce",
      code: "FSS_019",
      id: "019",
      continuousAssessmentScore: result[25],
      examScore: result[26],
      totalWeightedAverage: result[27],
    },

    {
      name: "Data Processing",
      code: "FSS_010",
      id: "010",
      continuousAssessmentScore: result[28],
      examScore: result[29],
      totalWeightedAverage: result[30],
    },
    {
      name: "Economics",
      code: "FSS_013",
      id: "013",
      continuousAssessmentScore: result[31],
      examScore: result[32],
      totalWeightedAverage: result[33],
    },
    {
      name: "English Language",
      code: "FSS_001",
      id: "001",
      continuousAssessmentScore: result[34],
      examScore: result[35],
      totalWeightedAverage: result[36],
    },
    {
      name: "Further Mathematics",
      code: "FSS_006",
      id: "006",
      continuousAssessmentScore: result[37],
      examScore: result[38],
      totalWeightedAverage: result[39],
    },
    {
      name: "Geography",
      code: "FSS_014",
      id: "014",
      continuousAssessmentScore: result[40],
      examScore: result[41],
      totalWeightedAverage: result[42],
    },
    {
      name: "Government",
      code: "FSS_016",
      id: "016",
      continuousAssessmentScore: result[43],
      examScore: result[44],
      totalWeightedAverage: result[45],
    },
    {
      name: "I.R.S",
      code: "FSS_011",
      id: "011",
      continuousAssessmentScore: result[46],
      examScore: result[47],
      totalWeightedAverage: result[48],
    },
    {
      name: "Literature in English",
      code: "FSS_017",
      id: "017",
      continuousAssessmentScore: result[49],
      examScore: result[50],
      totalWeightedAverage: result[51],
    },
    {
      name: "Marketing",
      code: "FSS_002",
      id: "022",
      continuousAssessmentScore: result[50],
      examScore: result[51],
      totalWeightedAverage: result[52],
    },
    {
      name: "Mathematics",
      code: "FSS_002",
      id: "002",
      continuousAssessmentScore: result[53],
      examScore: result[54],
      totalWeightedAverage: result[55],
    },

    {
      name: "Physics",
      code: "FSS_004",
      id: "004",
      continuousAssessmentScore: result[56],
      examScore: result[57],
      totalWeightedAverage: result[58],
    },
    {
      name: "Yoruba Language",
      code: "FSS_007",
      id: "007",
      continuousAssessmentScore: result[59],
      examScore: result[60],
      totalWeightedAverage: result[61],
    },
  ];
}

export function elementaryPerformance(result) {
  return [
    {
      name: "Number Work",
      code: "FES_001",
      id: "001",
      continuousAssessmentScore: result[1],
      examScore: result[2],
      totalWeightedAverage: result[3],
    },
    {
      name: "Letter Work",
      code: "FES_002",
      id: "002",
      continuousAssessmentScore: result[4],
      examScore: result[5],
      totalWeightedAverage: result[6],
    },
    {
      name: "Handwritting",
      code: "FES_003",
      id: "003",
      continuousAssessmentScore: result[7],
      examScore: result[8],
      totalWeightedAverage: result[9],
    },
    {
      name: "Communication Ability",
      code: "FES_004",
      id: "004",
      continuousAssessmentScore: result[10],
      examScore: result[11],
      totalWeightedAverage: result[12],
    },
    {
      name: "Rhymes and Poems",
      code: "FES_005",
      id: "005",
      continuousAssessmentScore: result[13],
      examScore: result[14],
      totalWeightedAverage: result[15],
    },
    {
      name: "Islamic Ethics/Arabic",
      code: "FES_006",
      id: "006",
      continuousAssessmentScore: result[16],
      examScore: result[17],
      totalWeightedAverage: result[18],
    },
    {
      name: "Social Norms: Manners / Morals",
      code: "FES_007",
      id: "007",
      continuousAssessmentScore: result[19],
      examScore: result[20],
      totalWeightedAverage: result[21],
    },
    {
      name: "Creative Activities / Ideas / Arts",
      code: "FES_008",
      id: "008",
      continuousAssessmentScore: result[22],
      examScore: result[23],
      totalWeightedAverage: result[24],
    },
    {
      name: "Physical Work",
      code: "FES_009",
      id: "009",
      continuousAssessmentScore: result[25],
      examScore: result[26],
      totalWeightedAverage: result[27],
    },
    {
      name: "DEEN",
      code: "FES_010",
      id: "010",
      continuousAssessmentScore: result[28],
      examScore: result[29],
      totalWeightedAverage: result[30],
    },
    {
      name: "COMPUTER",
      code: "FES_011",
      id: "011",
      continuousAssessmentScore: result[31],
      examScore: result[32],
      totalWeightedAverage: result[33],
    },
    {
      name: "Practical Life",
      code: "FES_012",
      id: "012",
      continuousAssessmentScore: result[34],
      examScore: result[35],
      totalWeightedAverage: result[36],
    },
    {
      name: "Health Habit",
      code: "FES_013",
      id: "013",
      continuousAssessmentScore: result[37],
      examScore: result[38],
      totalWeightedAverage: result[39],
    },
    {
      name: "Nature Study",
      code: "FES_014",
      id: "014",
      continuousAssessmentScore: result[40],
      examScore: result[41],
      totalWeightedAverage: result[42],
    },
  ];
}

export function basicPerformance(result) {
  return [
    {
      name: "English Language",
      code: "FBS_001",
      id: "001",
      continuousAssessmentScore: result[1],
      examScore: result[2],
      totalWeightedAverage: result[3],
    },
    {
      name: "Mathematics",
      code: "FBS_002",
      id: "002",
      continuousAssessmentScore: result[4],
      examScore: result[5],
      totalWeightedAverage: result[6],
    },
    {
      name: "Quantitative Reasoning",
      code: "FBS_003",
      id: "003",
      continuousAssessmentScore: result[7],
      examScore: result[8],
      totalWeightedAverage: result[9],
    },
    {
      name: "Verbal Reasoning",
      code: "FBS_004",
      id: "004",
      continuousAssessmentScore: result[10],
      examScore: result[11],
      totalWeightedAverage: result[12],
    },
    {
      name: "Arabic",
      code: "FBS_022",
      id: "022",
      continuousAssessmentScore: result[13],
      examScore: result[14],
      totalWeightedAverage: result[15],
    },
    {
      name: "Quran and Hadith",
      code: "FBS_006",
      id: "006",
      continuousAssessmentScore: result[16],
      examScore: result[17],
      totalWeightedAverage: result[18],
    },
    {
      name: "Handwritting",
      code: "FBS_005",
      id: "005",
      continuousAssessmentScore: result[19],
      examScore: result[20],
      totalWeightedAverage: result[21],
    },
    {
      name: "Fine Art",
      code: "FBS_007",
      id: "007",
      continuousAssessmentScore: result[22],
      examScore: result[23],
      totalWeightedAverage: result[24],
    },
    {
      name: "Civic Education ",
      code: "FBS_008",
      id: "008",
      continuousAssessmentScore: result[25],
      examScore: result[26],
      totalWeightedAverage: result[27],
    },
    {
      name: "P.H.E",
      code: "FBS_009",
      id: "009",
      continuousAssessmentScore: result[28],
      examScore: result[29],
      totalWeightedAverage: result[30],
    },
    {
      name: "Home Economics",
      code: "FBS_010",
      id: "010",
      continuousAssessmentScore: result[31],
      examScore: result[32],
      totalWeightedAverage: result[33],
    },
    {
      name: "I.R.S",
      code: "FBS_011",
      id: "011",
      continuousAssessmentScore: result[34],
      examScore: result[35],
      totalWeightedAverage: result[36],
    },
    {
      name: "Moral Instruction",
      code: "FBS_012",
      id: "012",
      continuousAssessmentScore: result[37],
      examScore: result[38],
      totalWeightedAverage: result[39],
    },
    {
      name: "Social Studies",
      code: "FBS_013",
      id: "013",
      continuousAssessmentScore: result[40],
      examScore: result[41],
      totalWeightedAverage: result[42],
    },
    {
      name: "Basic Science",
      code: "FBS_014",
      id: "014",
      continuousAssessmentScore: result[43],
      examScore: result[44],
      totalWeightedAverage: result[45],
    },
    {
      name: "Agric. Science",
      code: "FBS_015",
      id: "015",
      continuousAssessmentScore: result[46],
      examScore: result[47],
      totalWeightedAverage: result[48],
    },
    {
      name: "Computer Education",
      code: "FBS_016",
      id: "016",
      continuousAssessmentScore: result[49],
      examScore: result[50],
      totalWeightedAverage: result[51],
    },
    {
      name: "French",
      code: "FBS_017",
      id: "017",
      continuousAssessmentScore: result[52],
      examScore: result[53],
      totalWeightedAverage: result[54],
    },
    {
      name: "Yoruba",
      code: "FBS_018",
      id: "018",
      continuousAssessmentScore: result[55],
      examScore: result[56],
      totalWeightedAverage: result[57],
    },
    {
      name: "Vocational",
      code: "FBS_019",
      id: "019",
      continuousAssessmentScore: result[58],
      examScore: result[59],
      totalWeightedAverage: result[60],
    },
    {
      name: "Diction",
      code: "FBS_020",
      id: "020",
      continuousAssessmentScore: result[61],
      examScore: result[62],
      totalWeightedAverage: result[63],
    },
    {
      name: "History",
      code: "FBS_021",
      id: "021",
      continuousAssessmentScore: result[64],
      examScore: result[65],
      totalWeightedAverage: result[66],
    },
  ];
}
