export const seniorSchoolSubjects = [
  "Accounting",
  "Agriculture",
  "Animal Husbandry",
  "Arabic",
  "Biology",
  "Catering Craft Practice",
  "Chemistry",
  "Civic Education",
  "Commerce",
  "Data Processing",
  "Economics",
  "English Language",
  "Further Mathematics",
  "Geography",
  "Government",
  "IRS",
  "Literature In English",
  "Marketing",
  "Mathematics",
  "Physics",
  "Yoruba Language",
];

export const juniorSchoolSubjects = [
  "English Language",
  "Mathematics",
  "Qualitative Reasoning",
  "Verbal Reasoning",
  "Arabic",
];
export const allSubjects = [
  "Accounting",
  "Agriculture",
  "Animal Husbandry",
  "Arabic",
  "Biology",
  "Catering Craft Practice",
  "Chemistry",
  "Civic Education",
  "Commerce",
  "Data Processing",
  "Economics",
  "English Language",
  "Further Mathematics",
  "Geography",
  "Government",
  "IRS",
  "Literature In English",
  "Marketing",
  "Mathematics",
  "Physics",
  "Yoruba Language",
];
